/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.jdialog.NakladniAuto;
import gui.jdialog.OdeberAuto;
import gui.jdialog.NajdiSPZ;
import gui.jdialog.OsobniAuto;
import auta.IAutomobil;
import auta.ISeznamAutomobilu;
import auta.NakladniAutomobil;
import auta.OsobniAutomobil;
import auta.SeznamAut;
import auta.SouborCteni;
import auta.SouborUlozNactiStav;
import auta.TypAutomobilu;
import auta.UmyjNakladniAuta;
import auta.UmyjOsobniAuta;
import gui.jdialog.VypisSeznam;

import java.io.IOException;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author J3BY
 */
public class Autobazar extends javax.swing.JFrame {

    SeznamAut seznam;
    IAutomobil[] frontaOS;
    IAutomobil[] frontaNak;

    public Autobazar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTlacitek = new javax.swing.JPanel();
        jButtonNactiSeznam = new javax.swing.JButton();
        jButtonOsoAut = new javax.swing.JButton();
        jButtonNakAut = new javax.swing.JButton();
        jButtonVypis = new javax.swing.JButton();
        jButtonZrus = new javax.swing.JButton();
        jButtonNajdi = new javax.swing.JButton();
        jButtonOdeber = new javax.swing.JButton();
        jButtonUlozStav = new javax.swing.JButton();
        jButtonNactiStav = new javax.swing.JButton();
        jButtonVypisStav = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonUmyjOsAuta = new javax.swing.JButton();
        jButtonUmyjNaklAuta = new javax.swing.JButton();
        jButtonUmyto = new javax.swing.JButton();
        jScrollPaneVystup = new javax.swing.JScrollPane();
        jTextAreaVystup = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autobazar Jebavy");
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(1200, 525));

        jPanelTlacitek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelTlacitek.setPreferredSize(new java.awt.Dimension(170, 251));

        jButtonNactiSeznam.setText("Načti seznam");
        jButtonNactiSeznam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNactiSeznamActionPerformed(evt);
            }
        });

        jButtonOsoAut.setText("Vlož osobní auto");
        jButtonOsoAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOsoAutActionPerformed(evt);
            }
        });

        jButtonNakAut.setText("Vlož nákladní auto");
        jButtonNakAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNakAutActionPerformed(evt);
            }
        });

        jButtonVypis.setText("Vypiš seznam aut");
        jButtonVypis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVypisActionPerformed(evt);
            }
        });

        jButtonZrus.setText("Zruš seznam aut");
        jButtonZrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZrusActionPerformed(evt);
            }
        });

        jButtonNajdi.setText("Najdi automobil");
        jButtonNajdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNajdiActionPerformed(evt);
            }
        });

        jButtonOdeber.setText("Odeber automobil");
        jButtonOdeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdeberActionPerformed(evt);
            }
        });

        jButtonUlozStav.setText("Ulož stav");
        jButtonUlozStav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozStavActionPerformed(evt);
            }
        });

        jButtonNactiStav.setText("Načti stav");
        jButtonNactiStav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNactiStavActionPerformed(evt);
            }
        });

        jButtonVypisStav.setText("Vypiš stav seznamu");
        jButtonVypisStav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVypisStavActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonUmyjOsAuta.setText("Umyj osobní auta");
        jButtonUmyjOsAuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUmyjOsAutaActionPerformed(evt);
            }
        });

        jButtonUmyjNaklAuta.setText("Umyj nákladní auta");
        jButtonUmyjNaklAuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUmyjNaklAutaActionPerformed(evt);
            }
        });

        jButtonUmyto.setText("Umyto");
        jButtonUmyto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUmytoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUmyjOsAuta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonUmyjNaklAuta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonUmyto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUmyjOsAuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUmyjNaklAuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUmyto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTlacitekLayout = new javax.swing.GroupLayout(jPanelTlacitek);
        jPanelTlacitek.setLayout(jPanelTlacitekLayout);
        jPanelTlacitekLayout.setHorizontalGroup(
            jPanelTlacitekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTlacitekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTlacitekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNakAut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVypis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNajdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOdeber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonZrus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUlozStav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNactiStav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVypisStav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOsoAut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNactiSeznam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTlacitekLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTlacitekLayout.setVerticalGroup(
            jPanelTlacitekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTlacitekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNactiSeznam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOsoAut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNakAut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVypis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNajdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOdeber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonZrus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUlozStav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNactiStav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVypisStav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelTlacitek, java.awt.BorderLayout.LINE_START);

        jScrollPaneVystup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneVystup.setPreferredSize(new java.awt.Dimension(400, 100));

        jTextAreaVystup.setColumns(20);
        jTextAreaVystup.setRows(5);
        jTextAreaVystup.setText("PRÁZDNÝ SEZNAM");
        jTextAreaVystup.setToolTipText("");
        jTextAreaVystup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextAreaVystup.setDoubleBuffered(true);
        jTextAreaVystup.setEnabled(false);
        jTextAreaVystup.setFocusable(false);
        jScrollPaneVystup.setViewportView(jTextAreaVystup);

        getContentPane().add(jScrollPaneVystup, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNactiSeznamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNactiSeznamActionPerformed
        SouborCteni cti = new SouborCteni();
        String vypis = cti.cteniZeSouboru("seznam.txt");
        seznam = SeznamAut.getInstance();
        try {
            seznam.nactiSeznam(vypis);
            jTextAreaVystup.setText("");
        } catch (ISeznamAutomobilu.AutomobilSeznamException | ParseException ex) {
            Logger.getLogger(Autobazar.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Seznam se úspesně načetl");


    }//GEN-LAST:event_jButtonNactiSeznamActionPerformed

    private void jButtonNakAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNakAutActionPerformed
        NakladniAuto dialog = new NakladniAuto(this, true);
        if (seznam == null) {
            seznam = SeznamAut.getInstance();
        }
        dialog.setSeznam(seznam);
        dialog.setVisible(true);
        seznam = dialog.getSeznam();
        jTextAreaVystup.setText("");
    }//GEN-LAST:event_jButtonNakAutActionPerformed

    private void jButtonVypisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVypisActionPerformed
        if (seznam != null) {
            VypisSeznam dialog = new VypisSeznam(this, true);
            dialog.setVisible(true);
            IAutomobil[] poleAut = seznam.getPoleAutomobilu();
            String text = "";
            text = "TYP\t\tROK VYROBY\t\tSPZ\tSTAV TACHOMETRU [km]\tDATUM MYTÍ\t\tDELKA [m]\tBARVA\n\n";
            for (int i = 0; i < poleAut.length; i++) {

                if (poleAut[i] instanceof OsobniAutomobil && dialog.isPravdaOsAuta() == true) {
                    OsobniAutomobil os = (OsobniAutomobil) seznam.vratAuto(poleAut, i);
                    text += os.toString();
                }
                if (poleAut[i] instanceof NakladniAutomobil && dialog.isPravdaNaklAuta() == true) {
                    NakladniAutomobil nakl = (NakladniAutomobil) seznam.vratAuto(poleAut, i);
                    text += nakl.toString();
                }

            }
            jTextAreaVystup.setText(text);
        } else {
            JOptionPane.showMessageDialog(this, "Seznam je prazdný");
        }
    }//GEN-LAST:event_jButtonVypisActionPerformed

    private void jButtonZrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZrusActionPerformed
        int pravda = JOptionPane.showConfirmDialog(this, "Opravdu chcete zrušit seznam");
        if (pravda == 0) {
            seznam.zrusCelySeznamAut();
            JOptionPane.showMessageDialog(this, "Seznam vymazán");
            jTextAreaVystup.setText("PRAZDNÝ SEZNAM");
        } else {
            JOptionPane.showMessageDialog(this, "Akce zrušena uživatelem");
        }


    }//GEN-LAST:event_jButtonZrusActionPerformed

    private void jButtonNajdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNajdiActionPerformed
        NajdiSPZ dialog = new NajdiSPZ(this, true);
        dialog.setSeznam(seznam);
        dialog.setVisible(true);

    }//GEN-LAST:event_jButtonNajdiActionPerformed

    private void jButtonOdeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdeberActionPerformed
        if (seznam != null) {
            OdeberAuto dialog = new OdeberAuto(this, true);
            dialog.setSeznam(seznam);
            dialog.setVisible(true);
            seznam = dialog.getSeznam();
        } else {
            JOptionPane.showMessageDialog(this, "Seznam je prazdný. Nelze nic odebrat");
            jTextAreaVystup.setText("PRAZDNÝ SEZNAM");
        }
    }//GEN-LAST:event_jButtonOdeberActionPerformed

    private void jButtonUlozStavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozStavActionPerformed
        try {
            SouborUlozNactiStav.uloz("SeznamStav.obj", seznam);
            JOptionPane.showMessageDialog(this, "Stav seznamu ulozen do souboru SeznamStav.obj");
        } catch (IOException ex) {
            Logger.getLogger(Autobazar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUlozStavActionPerformed

    private void jButtonNactiStavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNactiStavActionPerformed
        try {
            if (seznam == null) {
                seznam = SeznamAut.getInstance();
            }
            seznam = SouborUlozNactiStav.nacti("SeznamStav.obj", seznam);
            JOptionPane.showMessageDialog(this, "Soubor  SeznamStav.obj  byl úspěšně načten");
            jTextAreaVystup.setText("");
        } catch (IOException | ISeznamAutomobilu.AutomobilSeznamException ex) {
            Logger.getLogger(Autobazar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNactiStavActionPerformed

    private void jButtonVypisStavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVypisStavActionPerformed
        if (seznam != null) {
            IAutomobil[] poleOsobnichAut = seznam.getPoleAutomobilu(TypAutomobilu.OSOBNI_AUTOMOBIL);
            IAutomobil[] poleNakladnichAut = seznam.getPoleAutomobilu(TypAutomobilu.NAKLADNI_AUTOMOBIL);
            String text = "";
            text += "Celkový počet aut v seznamu:\t" + (poleOsobnichAut.length + poleNakladnichAut.length) + "\n\n";
            text += "Počet osobních automobilů:\t" + (poleOsobnichAut.length) + "\n";
            text += "Počet nákládních automobilů:\t" + (poleNakladnichAut.length) + "\n";
            jTextAreaVystup.setText(text);
        }else{
            jTextAreaVystup.setText("PRAZDNÝ SEZNAM");
        }
    }//GEN-LAST:event_jButtonVypisStavActionPerformed

    private void jButtonOsoAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOsoAutActionPerformed
        OsobniAuto dialog = new OsobniAuto(this, true);
        if (seznam == null) {
            seznam = SeznamAut.getInstance();
        }
        dialog.setSeznam(seznam);
        dialog.setVisible(true);
        seznam = dialog.getSeznam();
        jTextAreaVystup.setText("");


    }//GEN-LAST:event_jButtonOsoAutActionPerformed

    private void jButtonUmytoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUmytoActionPerformed
        UmyjOsobniAuta osAuta = new UmyjOsobniAuta(seznam);
        UmyjNakladniAuta naklAuto = new UmyjNakladniAuta(seznam);
        try {
            if (frontaOS != null) {
                osAuta.nastavCasMyti(seznam, frontaOS);
            }
            if (frontaNak != null) {
                naklAuto.nastavCasMyti(seznam, frontaNak);
            }

            JOptionPane.showMessageDialog(this, "Vybraná auta byla umyta.");
            jTextAreaVystup.setText("");
            frontaNak = null;
            frontaOS = null;
        } catch (ISeznamAutomobilu.AutomobilSeznamException | ParseException ex) {
            Logger.getLogger(Autobazar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUmytoActionPerformed

    private void jButtonUmyjOsAutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUmyjOsAutaActionPerformed
        if (seznam != null) {

            String text = "";
            if (frontaNak != null) {
                text += jTextAreaVystup.getText();
            }
            UmyjOsobniAuta osAuta = new UmyjOsobniAuta(seznam);
            frontaOS = osAuta.vratFrontu();
            text += "FRONTA NA UMITÍ OSOBNÍCH AUT\n\n";
            text += "TYP\t\tROK VYROBY\t\tSPZ\tSTAV TACHOMETRU [km]\tDATUM MYTÍ\t\tDELKA [m]\tBARVA\n\n";
            for (int i = 0; i < frontaOS.length; i++) {
                OsobniAutomobil os = (OsobniAutomobil) seznam.vratAuto(frontaOS, i);
                text += os.toString();

            }
            text += "\n\n";
            jTextAreaVystup.setText(text);
        }
    }//GEN-LAST:event_jButtonUmyjOsAutaActionPerformed

    private void jButtonUmyjNaklAutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUmyjNaklAutaActionPerformed
        if (seznam != null) {
            String text = "";
            if (frontaOS != null) {
                text += jTextAreaVystup.getText();
            }
            UmyjNakladniAuta osNakl = new UmyjNakladniAuta(seznam);
            frontaNak = osNakl.vratFrontu();
            text += "FRONTA NA UMITÍ NÁKLADNÍCH AUT\n\n";
            text += "TYP\t\tROK VYROBY\t\tSPZ\tSTAV TACHOMETRU [km]\tDATUM MYTÍ\t\tDELKA [m]\tBARVA\n\n";
            for (int i = 0; i < frontaNak.length; i++) {
                NakladniAutomobil nakl = (NakladniAutomobil) seznam.vratAuto(frontaNak, i);
                text += nakl.toString();
            }
            text += "\nCelková délka na umití za pracovní dobu 8h(1m/5minut): " + osNakl.getDelka() + "\n\n\n";

            jTextAreaVystup.setText(text);
        }
    }//GEN-LAST:event_jButtonUmyjNaklAutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autobazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autobazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autobazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autobazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autobazar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNactiSeznam;
    private javax.swing.JButton jButtonNactiStav;
    private javax.swing.JButton jButtonNajdi;
    private javax.swing.JButton jButtonNakAut;
    private javax.swing.JButton jButtonOdeber;
    private javax.swing.JButton jButtonOsoAut;
    private javax.swing.JButton jButtonUlozStav;
    private javax.swing.JButton jButtonUmyjNaklAuta;
    private javax.swing.JButton jButtonUmyjOsAuta;
    private javax.swing.JButton jButtonUmyto;
    private javax.swing.JButton jButtonVypis;
    private javax.swing.JButton jButtonVypisStav;
    private javax.swing.JButton jButtonZrus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTlacitek;
    private javax.swing.JScrollPane jScrollPaneVystup;
    private javax.swing.JTextArea jTextAreaVystup;
    // End of variables declaration//GEN-END:variables
}
