/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panely;

import databaze.OracleConnector;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dex
 */
public class PrehledZnameni extends javax.swing.JPanel implements ObnovitelnyPanel{

    /**
     * Creates new form PrehledZnameni
     */
    public PrehledZnameni() {
        initComponents();
        initZnameni();
    }

    private void initZnameni(){
         initComponents();
        try {
            String[] columnNames = {"ID_ZNAMENI", "DATUM_OD", "DATUM_DO", "POPIS"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            PreparedStatement pstmt = OracleConnector.getConnection().prepareStatement("select ID_ZNAMENI, to_char(DATUM_OD, 'DD. MM.'), to_char(DATUM_DO, 'DD. MM.'), POPIS" 
                    + " from SP_ZNAMENI"
                    + " order by datum_OD asc");
            ResultSet rset = pstmt.executeQuery();

            while (rset.next()) {
                Vector<String> row = new Vector();
                for (int i = 1; i <= columnNames.length; i++) {
                    row.add(rset.getString(i)); // vytvoreni radku tabulky ze ziskanych hodnot
                }
                model.addRow(row); // pridani radku do modelu

            }
            jTable1.setModel(model);

        } catch (SQLException ex) {
            String textChyby = "Chyba při vykreslování přehledu znamení! " + ex.toString();
            System.err.println(textChyby);
        }        
    }

    @Override
    public void repaint() {
        super.repaint(); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void obnovTabulku() {
        initZnameni();
    }
}
