/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panely;

import databaze.MyDBProperties;
import databaze.OracleConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dex
 */
public class UkolyUzivatele extends javax.swing.JPanel implements ObnovitelnyPanel {

    private int PRIHLASENY_UZIVATEL_ID;
    public int pocetUkolu;

    /**
     * Creates new form ukolyUzivatele
     */
    public UkolyUzivatele(int idUzivatele) {
        PRIHLASENY_UZIVATEL_ID = idUzivatele;
        initComponents();
        initTable();
    }

    private void initTable() {
        pocetUkolu = 0;
        Statement stmt = null;
        String[] columnsName = {"ID", "Název", "Popis", "Vytvořeno", "Deadline", "Priorita"};
        DefaultTableModel model = new DefaultTableModel(columnsName, 0);
        String query = "select id_ukolu ID, NAZEV Název, POPIS,"
                + " to_char(DATUM_VYTVORENI, 'DD. MM. YYYY HH24:MI') Vytvořeno,"
                + " to_char(DEADLINE, 'DD. MM. YYYY HH24:MI') Deadline, ID_PRIORITY Priorita"
                + " from " + MyDBProperties.MYNAME + "." + MyDBProperties.UKOLY
                + " left join " + MyDBProperties.MYNAME + "." + MyDBProperties.UKOLY_UZIVATELU + " using(ID_UKOLU)"
                + " where id_uzivatele = '" + PRIHLASENY_UZIVATEL_ID + "'"
                + " order by Vytvořeno desc";
        try {
            stmt = OracleConnector.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                Vector<String> row = new Vector();
                for (String columnName : columnsName) {
                    row.add(rs.getString(columnName));
                }
                model.addRow(row);
                pocetUkolu++;
            }
            jTable1.setModel(model);
            if (pocetUkolu == 0) {
                jLabel1.setText("Vítej! Dnes nemusíš dělat vůbec nic!");
            } else {
                jLabel1.setText("Vítej! Máš na práci " + pocetUkolu + " úkolů!");
            }
            repaint();
        } catch (SQLException ex) {
            String textChyby = "Chyba při vykreslování všech úkolů! " + ex.toString();
            System.out.println(textChyby);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ahoj!");
        jLabel1.setMaximumSize(new java.awt.Dimension(26, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(26, 20));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void obnovTabulku() {
        initTable();
    }
}
