package panely;

import databaze.MyDBProperties;
import databaze.OracleConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

public class VsechnyUkoly extends javax.swing.JPanel implements ObnovitelnyPanel{

    /**
     * Creates new form VsechnyUkoly
     */
    public VsechnyUkoly() {
        initComponents();
        vykresliVsechnyUkoly();
    }

    private void vykresliVsechnyUkoly() {
        Statement stmt = null;
        String[] columnsName = {"ID", "Název", "Popis", "Vytvořeno", "Deadline", "Priorita", "Stav"};
        DefaultTableModel model = new DefaultTableModel(columnsName, 0);
        String query = "select id_ukolu ID, SP_UKOLY.NAZEV Název, SP_UKOLY.POPIS, to_char(DATUM_VYTVORENI, 'DD. MM. YYYY HH24:MI') Vytvořeno,"
                + " to_char(DEADLINE, 'DD. MM. YYYY HH24:MI') Deadline, ID_PRIORITY Priorita, "
                + " SP_STAVY.NAZEV Stav"
                + " from " + MyDBProperties.MYNAME + "." + MyDBProperties.UKOLY
                + " left join " + MyDBProperties.MYNAME + "." + MyDBProperties.STAVY + " using(ID_STAV)"
                + " order by Vytvořeno desc";
        try {
            stmt = OracleConnector.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                Vector<String> row = new Vector();
                for (String columnName : columnsName) {
                    row.add(rs.getString(columnName));
                }
                model.addRow(row);
            }
            jTable1.setModel(model);
        } catch (SQLException ex) {
            String textChyby = "Chyba při vykreslování všech úkolů! " + ex.toString();
            System.err.println(textChyby);
        }
    }

    @Override
    public void repaint() {
        super.repaint(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public int getSelectedRow() {
        return jTable1.getSelectedRow();
    }

    public int getIDUkol(int vysledek) {
        return Integer.parseInt((String) jTable1.getValueAt(vysledek, 0));
    }

    @Override
    public void obnovTabulku() {
        vykresliVsechnyUkoly();
    }

}
