/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.jdialog;

import pobocka.EnumPozice;

/**
 *
 * @author st39740
 */
public class JDPobocka extends javax.swing.JDialog {
    private EnumPozice pozice = null;
    private String nazev;
    
    
    
    /**
     * Creates new form Pobocka
     */
    public JDPobocka(java.awt.Frame parent, boolean modal, int cislo) {
        super(parent, modal);
        initComponents();
        jTextFieldNazev.setText("Pobocka " + cislo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPozice = new javax.swing.ButtonGroup();
        jPanelVyberu = new javax.swing.JPanel();
        jRadioButtonPrvni = new javax.swing.JRadioButton();
        jRadioButtonPosledni = new javax.swing.JRadioButton();
        jRadioButtonPredchudce = new javax.swing.JRadioButton();
        jRadioButtonNaslednik = new javax.swing.JRadioButton();
        jButtonOK = new javax.swing.JButton();
        jTextFieldNazev = new javax.swing.JTextField();
        jLabelPopisek = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vlož pobočku");
        setPreferredSize(new java.awt.Dimension(300, 200));

        jPanelVyberu.setBorder(javax.swing.BorderFactory.createTitledBorder("Vlož na pozici"));
        jPanelVyberu.setPreferredSize(new java.awt.Dimension(120, 129));

        buttonGroupPozice.add(jRadioButtonPrvni);
        jRadioButtonPrvni.setSelected(true);
        jRadioButtonPrvni.setText("První");

        buttonGroupPozice.add(jRadioButtonPosledni);
        jRadioButtonPosledni.setText("Poslední");

        buttonGroupPozice.add(jRadioButtonPredchudce);
        jRadioButtonPredchudce.setText("Předchůdce");

        buttonGroupPozice.add(jRadioButtonNaslednik);
        jRadioButtonNaslednik.setText("Následník");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jTextFieldNazev.setText("Pobocka");

        jLabelPopisek.setText("Název pobočky");

        javax.swing.GroupLayout jPanelVyberuLayout = new javax.swing.GroupLayout(jPanelVyberu);
        jPanelVyberu.setLayout(jPanelVyberuLayout);
        jPanelVyberuLayout.setHorizontalGroup(
            jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVyberuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVyberuLayout.createSequentialGroup()
                        .addComponent(jRadioButtonPosledni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110))
                    .addGroup(jPanelVyberuLayout.createSequentialGroup()
                        .addGroup(jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVyberuLayout.createSequentialGroup()
                                .addComponent(jRadioButtonNaslednik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addComponent(jRadioButtonPredchudce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelVyberuLayout.createSequentialGroup()
                                .addComponent(jRadioButtonPrvni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVyberuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNazev)
                                    .addComponent(jLabelPopisek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(3, 3, 3))
                            .addGroup(jPanelVyberuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelVyberuLayout.setVerticalGroup(
            jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVyberuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVyberuLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelPopisek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRadioButtonPrvni))
                .addGap(1, 1, 1)
                .addGroup(jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVyberuLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldNazev))
                    .addComponent(jRadioButtonPosledni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPredchudce, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                .addGroup(jPanelVyberuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNaslednik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanelVyberu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        boolean prvni = jRadioButtonPrvni.isSelected();
        boolean posledni = jRadioButtonPosledni.isSelected();
        boolean predchudce = jRadioButtonPredchudce.isSelected();
        boolean naslednik = jRadioButtonNaslednik.isSelected();
        if (prvni) {
            pozice = EnumPozice.PRVNI;
        }else if(posledni){
            pozice = EnumPozice.POSLEDNI;
        }else if(predchudce){
            pozice = EnumPozice.PREDCHUDCE;
        }else if(naslednik){
            pozice = EnumPozice.NASLEDNIK;
        }
        nazev = jTextFieldNazev.getText();
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    public EnumPozice getPozice() {
        return pozice;
    }

    public String getNazev() {
        return nazev;
    }
    
    public void upravitPobocku(){
        jButtonOK.setText("Změnit");
        jPanelVyberu.setEnabled(false);
        jRadioButtonPrvni.setEnabled(false);
        jRadioButtonPosledni.setEnabled(false);
        jRadioButtonPredchudce.setEnabled(false);
        jRadioButtonNaslednik.setEnabled(false);
        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDPobocka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDPobocka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDPobocka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDPobocka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDPobocka dialog = new JDPobocka(new javax.swing.JFrame(), true,WIDTH);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPozice;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelPopisek;
    private javax.swing.JPanel jPanelVyberu;
    private javax.swing.JRadioButton jRadioButtonNaslednik;
    private javax.swing.JRadioButton jRadioButtonPosledni;
    private javax.swing.JRadioButton jRadioButtonPredchudce;
    private javax.swing.JRadioButton jRadioButtonPrvni;
    private javax.swing.JTextField jTextFieldNazev;
    // End of variables declaration//GEN-END:variables
}
