/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.jdialog;

import auta.IAuto;
import auta.Uzitkova;
import pobocka.EnumPozice;

/**
 *
 * @author J3BY
 */
public class JDUzitkoveAuto extends javax.swing.JDialog {

    private String spz;
    private int stavTachometru, pocetVypujceni, nosnost;
    private IAuto uzitkove;
    private boolean vytvorit = true;

    /**
     * Creates new form OsobniAuto
     */
    public JDUzitkoveAuto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        predvypln();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPozice = new javax.swing.ButtonGroup();
        jButtonOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSPZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTachometr = new javax.swing.JTextField();
        jTextFieldPocetPujceni = new javax.swing.JTextField();
        jTextFieldNosnost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vlož užitkový automobil");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel1.setText("Nosnost:");

        jLabel3.setText("SPZ:");

        jTextFieldSPZ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSPZ.setText("ST-39740");

        jLabel4.setText("Stav tachometru:");

        jLabel5.setText("Počet vypůjčení:");

        jTextFieldTachometr.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTachometr.setText("100000");

        jTextFieldPocetPujceni.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPocetPujceni.setText("5");

        jTextFieldNosnost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldNosnost.setText("1500");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNosnost)
                            .addComponent(jTextFieldTachometr, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPocetPujceni, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSPZ, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSPZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNosnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTachometr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPocetPujceni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        spz = jTextFieldSPZ.getText();
        stavTachometru = Integer.valueOf(jTextFieldTachometr.getText());
        pocetVypujceni = Integer.valueOf(jTextFieldPocetPujceni.getText());
        nosnost = Integer.valueOf(jTextFieldNosnost.getText());
        if (vytvorit) {
            uzitkove = new Uzitkova(nosnost, spz, stavTachometru, pocetVypujceni);
        }
        this.setVisible(false);

    }//GEN-LAST:event_jButtonOKActionPerformed

    public void predvypln() {
        int tachometrPred = (int) (10000 + (50000 - 10000 + 1) * Math.random());
        int spzPred = (int) (20000 + (50000 - 20000 + 1) * Math.random());
        int pocetVypujceniPred = (int) (8 * Math.random());
        int nostnostPred = (int) (500 + (3500 - 500 + 1) * Math.random());

        jTextFieldTachometr.setText(Integer.toString(tachometrPred));
        jTextFieldSPZ.setText("ST-" + Integer.toString(spzPred));
        jTextFieldPocetPujceni.setText(Integer.toString(pocetVypujceniPred));
        jTextFieldNosnost.setText(Integer.toString(nostnostPred));
    }

    public IAuto getUzitkove() {
        return uzitkove;
    }


    public String getSpz() {
        return spz;
    }

    public int getStavTachometru() {
        return stavTachometru;
    }

    public int getPocetVypujceni() {
        return pocetVypujceni;
    }

    public int getNosnost() {
        return nosnost;
    }

    public void upravAuto(IAuto uzitkove) {
         setTitle("Uprav užitkový automobil");
        jButtonOK.setText("Změnit");

        jTextFieldNosnost.setText(Integer.toString(uzitkove.getNosnost()));
        jTextFieldPocetPujceni.setText(Integer.toString(uzitkove.getPocetVypujceni()));
        jTextFieldSPZ.setText(uzitkove.getSpz());
        jTextFieldTachometr.setText(Integer.toString(uzitkove.getPocetKilometru()));

        vytvorit = false;
        spz = uzitkove.getSpz();
        stavTachometru = uzitkove.getPocetKilometru();
        pocetVypujceni = uzitkove.getPocetVypujceni();
        nosnost = uzitkove.getNosnost();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDUzitkoveAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDUzitkoveAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDUzitkoveAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDUzitkoveAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUzitkoveAuto dialog = new JDUzitkoveAuto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPozice;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldNosnost;
    private javax.swing.JTextField jTextFieldPocetPujceni;
    private javax.swing.JTextField jTextFieldSPZ;
    private javax.swing.JTextField jTextFieldTachometr;
    // End of variables declaration//GEN-END:variables
}
