/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.jdialog;

import auta.IAutomobil;
import auta.ISeznamAutomobilu;
import auta.NakladniAutomobil;
import auta.OsobniAutomobil;
import auta.SeznamAut;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author J3BY
 */
public class NajdiSPZ extends javax.swing.JDialog {

    SeznamAut seznam;

    /**
     * Creates new form NajdiSPZ
     */
    public NajdiSPZ(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldHledanyVyraz = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonHledat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelHledanyVyraz = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vyhledej automobil");

        jTextFieldHledanyVyraz.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zadej SPZ:");

        jButtonHledat.setText("Hledat");
        jButtonHledat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHledatActionPerformed(evt);
            }
        });

        jLabelHledanyVyraz.setColumns(20);
        jLabelHledanyVyraz.setRows(5);
        jLabelHledanyVyraz.setEnabled(false);
        jScrollPane1.setViewportView(jLabelHledanyVyraz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldHledanyVyraz, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jButtonHledat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHledanyVyraz))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHledat, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addGap(74, 74, 74))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHledatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHledatActionPerformed
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy.MM.dd");
        SimpleDateFormat format2 = new SimpleDateFormat("yyyy");
        try {
            IAutomobil hledany = seznam.najdiAuto(jTextFieldHledanyVyraz.getText());
            if (hledany != null) {

                if (hledany instanceof OsobniAutomobil) {
                    OsobniAutomobil os = (OsobniAutomobil) hledany;
                    jLabelHledanyVyraz.setText("Osobní automobil\nRok výroby: "
                            + format2.format(os.getRokVyroby())+ "\nStav tachometru: " + os.getStavTachometru() + "\nSPZ: "
                            + os.getSpz() + "\nPosledni Mytí: " + format1.format(os.getDatumPoslednihoMyti()) + "\nBarva: " + os.getBarva());
                } else {
                    NakladniAutomobil nakl = (NakladniAutomobil) hledany;
                    jLabelHledanyVyraz.setText("Nákladní automobil\nRok výroby: "
                            + format2.format(nakl.getRokVyroby()) + "\nStav tachometru: " + nakl.getStavTachometru() + "\nSPZ: "
                            + nakl.getSpz() + "\nPosledni Mytí: " + format1.format(nakl.getDatumPoslednihoMyti()) + "\nDélka: " + nakl.getDelka());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nebylo nic nalezeno");
                jLabelHledanyVyraz.setText("Nic nenalezeno");
            }
        } catch (ISeznamAutomobilu.AutomobilSeznamException ex) {
            Logger.getLogger(NajdiSPZ.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonHledatActionPerformed

    public void setSeznam(SeznamAut seznam) {
        this.seznam = seznam;
    }

    public SeznamAut getSeznam() {
        return seznam;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NajdiSPZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NajdiSPZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NajdiSPZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NajdiSPZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NajdiSPZ dialog = new NajdiSPZ(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHledat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jLabelHledanyVyraz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldHledanyVyraz;
    // End of variables declaration//GEN-END:variables
}
