package gui.jdialog;

import auta.ISeznamAutomobilu;
import auta.NakladniAutomobil;
import auta.SeznamAut;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author J3BY
 */
public class NakladniAuto extends javax.swing.JDialog {

    SeznamAut seznam;

    /**
     * Creates new form NakladniAuto
     */
    public NakladniAuto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        predvypln();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUloz = new javax.swing.JButton();
        jButtonUlozDalsi = new javax.swing.JButton();
        jButtonKonec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDelka = new javax.swing.JTextField();
        jTextFieldRokVyroby = new javax.swing.JTextField();
        jTextFieldSPZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTachometr = new javax.swing.JTextField();
        jTextFieldMyti = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vlož nákladní automobil");

        jButtonUloz.setText("Ulož");
        jButtonUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozActionPerformed(evt);
            }
        });

        jButtonUlozDalsi.setText("Ulož a další auto");
        jButtonUlozDalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozDalsiActionPerformed(evt);
            }
        });

        jButtonKonec.setText("Konec");
        jButtonKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonecActionPerformed(evt);
            }
        });

        jLabel1.setText("Délka [m]:");

        jLabel2.setText("Rok vyroby:");

        jLabel3.setText("SPZ:");

        jTextFieldDelka.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDelka.setText("7");

        jTextFieldRokVyroby.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRokVyroby.setText("2014");
        jTextFieldRokVyroby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRokVyrobyActionPerformed(evt);
            }
        });

        jTextFieldSPZ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSPZ.setText("ST-39740");

        jLabel4.setText("Stav tachometru [km]:");

        jLabel5.setText("Posledni mytí:");

        jTextFieldTachometr.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTachometr.setText("100000");

        jTextFieldMyti.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMyti.setText("2014.12.24");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDelka))
                            .addComponent(jButtonUloz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTachometr, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRokVyroby, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSPZ)
                            .addComponent(jTextFieldMyti)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUlozDalsi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jButtonKonec, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDelka)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldRokVyroby)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSPZ))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldMyti)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTachometr))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUloz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUlozDalsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKonec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozActionPerformed
        String barva, spz, rokVyroby, stavTachometru, posledniMyti;
        barva = jTextFieldDelka.getText();
        spz = jTextFieldSPZ.getText();
        rokVyroby = jTextFieldRokVyroby.getText();
        stavTachometru = jTextFieldTachometr.getText();
        posledniMyti = jTextFieldMyti.getText();
        try {
            NakladniAutomobil nakl;
            nakl = seznam.vytvorNakl(barva, rokVyroby, spz, posledniMyti, stavTachometru);
            seznam.vlozAuto(nakl);
            JOptionPane.showMessageDialog(this, "Nákladní auto úspěšně vloženo");
            setVisible(false);
        } catch (ParseException | ISeznamAutomobilu.AutomobilSeznamException ex) {
            Logger.getLogger(OsobniAuto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonUlozActionPerformed

    private void jButtonUlozDalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozDalsiActionPerformed
        String delka, spz, rokVyroby, stavTachometru, posledniMyti;
        delka = jTextFieldDelka.getText();
        spz = jTextFieldSPZ.getText();
        rokVyroby = jTextFieldRokVyroby.getText();
        stavTachometru = jTextFieldTachometr.getText();
        posledniMyti = jTextFieldMyti.getText();
        try {
            NakladniAutomobil nakl;
            nakl = seznam.vytvorNakl(delka, rokVyroby, spz, posledniMyti, stavTachometru);
            seznam.vlozAuto(nakl);
            JOptionPane.showMessageDialog(this, "Nakladni auto úspěšně vloženo. Vložte další.");
            predvypln();
        } catch (ParseException | ISeznamAutomobilu.AutomobilSeznamException ex) {
            Logger.getLogger(OsobniAuto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUlozDalsiActionPerformed

    private void jButtonKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonecActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonKonecActionPerformed

    private void jTextFieldRokVyrobyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRokVyrobyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRokVyrobyActionPerformed
    public void setSeznam(SeznamAut seznam) {
        this.seznam = seznam;
    }

    public SeznamAut getSeznam() {
        return seznam;
    }
    public void predvypln() {
        int tachometr = (int) (10000 + (50000 - 10000 + 1) * Math.random());
        int rok = (int) (1980 + (2015 - 1980 + 1) * Math.random());
        int spz = (int) (20000 + (50000 - 20000 + 1) * Math.random());
        int den = (int) (1 + (30 - 1 + 1) * Math.random());
        int mesic = (int) (1 + (12 - 1 + 1) * Math.random());
        int delka = (int) (1 + (30 - 1 + 1) * Math.random());
       
        
 
        jTextFieldTachometr.setText(Integer.toString(tachometr));
        jTextFieldRokVyroby.setText(Integer.toString(rok));
        jTextFieldSPZ.setText("ST-" + Integer.toString(spz));
        jTextFieldMyti.setText(rok + "." + mesic + "." + den);
        jTextFieldDelka.setText(Integer.toString(delka));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NakladniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NakladniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NakladniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NakladniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NakladniAuto dialog = new NakladniAuto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKonec;
    private javax.swing.JButton jButtonUloz;
    private javax.swing.JButton jButtonUlozDalsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldDelka;
    private javax.swing.JTextField jTextFieldMyti;
    private javax.swing.JTextField jTextFieldRokVyroby;
    private javax.swing.JTextField jTextFieldSPZ;
    private javax.swing.JTextField jTextFieldTachometr;
    // End of variables declaration//GEN-END:variables
}
