/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.jdialog;

import auta.Barva;
import auta.ISeznamAutomobilu;
import auta.OsobniAutomobil;
import auta.SeznamAut;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author J3BY
 */
public class OsobniAuto extends javax.swing.JDialog {

    SeznamAut seznam;

    /**
     * Creates new form OsobniAuto
     */
    public OsobniAuto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        predvypln();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUloz = new javax.swing.JButton();
        jButtonUlozDalsi = new javax.swing.JButton();
        jButtonKonec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBarva = new javax.swing.JTextField();
        jTextFieldRokVyroby = new javax.swing.JTextField();
        jTextFieldSPZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTachometr = new javax.swing.JTextField();
        jTextFieldMyti = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vlož osobní automobil");

        jButtonUloz.setText("Ulož");
        jButtonUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozActionPerformed(evt);
            }
        });

        jButtonUlozDalsi.setText("Ulož a další auto");
        jButtonUlozDalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozDalsiActionPerformed(evt);
            }
        });

        jButtonKonec.setText("Konec");
        jButtonKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonecActionPerformed(evt);
            }
        });

        jLabel1.setText("Barva:");

        jLabel2.setText("Rok vyroby:");

        jLabel3.setText("SPZ:");

        jTextFieldBarva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldBarva.setText("BILA");

        jTextFieldRokVyroby.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRokVyroby.setText("2014");

        jTextFieldSPZ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSPZ.setText("ST-39740");

        jLabel4.setText("Stav tachometru:");

        jLabel5.setText("Posledni mytí:");

        jTextFieldTachometr.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTachometr.setText("100000");

        jTextFieldMyti.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMyti.setText("2014.12.24");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUloz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTachometr, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBarva, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRokVyroby)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonUlozDalsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKonec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSPZ)
                    .addComponent(jTextFieldMyti, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldBarva)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldRokVyroby)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSPZ))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldMyti)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTachometr))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUloz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUlozDalsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKonec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozActionPerformed
        String barva, spz, rokVyroby, stavTachometru, posledniMyti;
        barva = jTextFieldBarva.getText();
        spz = jTextFieldSPZ.getText();
        rokVyroby = jTextFieldRokVyroby.getText();
        stavTachometru = jTextFieldTachometr.getText();
        posledniMyti = jTextFieldMyti.getText();        
        try {
            OsobniAutomobil os;
            os = seznam.vytvorOS(barva, rokVyroby, spz, posledniMyti, stavTachometru);
            seznam.vlozAuto(os);
            
            JOptionPane.showMessageDialog(this, "Osobni auto úspěšně vloženo");
            setVisible(false);
        } catch (ParseException | ISeznamAutomobilu.AutomobilSeznamException ex) {
            
            Logger.getLogger(OsobniAuto.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        

    }//GEN-LAST:event_jButtonUlozActionPerformed

    private void jButtonKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonecActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonKonecActionPerformed

    private void jButtonUlozDalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozDalsiActionPerformed
        String barva, spz, rokVyroby, stavTachometru, posledniMyti;
        barva = jTextFieldBarva.getText();
        spz = jTextFieldSPZ.getText();
        rokVyroby = jTextFieldRokVyroby.getText();
        stavTachometru = jTextFieldTachometr.getText();
        posledniMyti = jTextFieldMyti.getText();        
        try {
            OsobniAutomobil os;
            os = seznam.vytvorOS(barva, rokVyroby, spz, posledniMyti, stavTachometru);
            seznam.vlozAuto(os);
            
            JOptionPane.showMessageDialog(this, "Osobni auto úspěšně vloženo. Vložte další.");
            predvypln();
        } catch (ParseException | ISeznamAutomobilu.AutomobilSeznamException ex) {
            Logger.getLogger(OsobniAuto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUlozDalsiActionPerformed
    
    public void setSeznam(SeznamAut seznam) {
        this.seznam = seznam;
    }
    
    public SeznamAut getSeznam() {
        return seznam;
    }
    

    public void predvypln() {
        int tachometr = (int) (10000 + (50000 - 10000 + 1) * Math.random());
        int rok = (int) (1980 + (2015 - 1980 + 1) * Math.random());
        int spz = (int) (20000 + (50000 - 20000 + 1) * Math.random());
        int den = (int) (1 + (30 - 1 + 1) * Math.random());
        int mesic = (int) (1 + (12 - 1 + 1) * Math.random());
        int cislo = (int) (1 + (5 - 1 + 1) * Math.random());
        String text = null;
        if (cislo > 0 && cislo < 6)
        {     
            switch(cislo){
                case 1: text = "CERNA";
                    break;
                case 2: text = "CERVENA";
                    break;
                case 3: text = "ZELENA";
                    break;
                case 4: text = "MODRA";
                    break;
                case 5: text = "BILA";
                    break;
            }
        }
 
        jTextFieldTachometr.setText(Integer.toString(tachometr));
        jTextFieldRokVyroby.setText(Integer.toString(rok));
        jTextFieldSPZ.setText("ST-" + Integer.toString(spz));
        jTextFieldMyti.setText(rok + "." + mesic + "." + den);
        jTextFieldBarva.setText(text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OsobniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OsobniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OsobniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OsobniAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OsobniAuto dialog = new OsobniAuto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKonec;
    private javax.swing.JButton jButtonUloz;
    private javax.swing.JButton jButtonUlozDalsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldBarva;
    private javax.swing.JTextField jTextFieldMyti;
    private javax.swing.JTextField jTextFieldRokVyroby;
    private javax.swing.JTextField jTextFieldSPZ;
    private javax.swing.JTextField jTextFieldTachometr;
    // End of variables declaration//GEN-END:variables
}
