package dialogy;

import databaze.MyDBProperties;
import databaze.OracleConnector;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dex
 */
public class AddTaskDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddTaskDialog
     */
    public AddTaskDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Přidání úkolu do databáze");
        initComboBoxStav();
        jComboBox1.setAlignmentX(CENTER_ALIGNMENT);
        jComboBox1.setAlignmentY(CENTER_ALIGNMENT);
    }

    private void initComboBoxStav(){
        Vector<String> vysledky = new Vector();
        Statement stmt;
        String query = "select NAZEV"
                + " from " + MyDBProperties.MYNAME + "." + MyDBProperties.STAVY
                + " order by ID_STAV asc";
        try {
            stmt = OracleConnector.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                vysledky.add(rs.getString("NAZEV"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AssignTasksDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(vysledky);
        jComboBox2.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vytvoření nového úkolu");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setText("Název úkolu:");
        jPanel1.add(jLabel2);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Stručný a výstižný název úkolu. Max 100 znaků.");
        jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        jPanel2.add(jTextField1);

        jPanel1.add(jPanel2);

        jLabel3.setText("Popis úkolu:");
        jPanel1.add(jLabel3);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setMinimumSize(new java.awt.Dimension(4, 300));
        jTextArea1.setPreferredSize(new java.awt.Dimension(104, 300));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);

        jLabel5.setText("Deadline");
        jPanel1.add(jLabel5);

        jPanel3.add(jCheckBox1);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jPanel3.add(jSpinner2);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jPanel3.add(jSpinner3);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(2016, 2016, 2030, 1));
        jPanel3.add(jSpinner4);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(24), Integer.valueOf(1)));
        jPanel3.add(jSpinner1);

        jLabel7.setText(":");
        jPanel3.add(jLabel7);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));
        jPanel3.add(jSpinner5);

        jPanel1.add(jPanel3);

        jLabel4.setText("Priorita");
        jPanel1.add(jLabel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vysoká", "Střední", "Nízká" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel1.add(jComboBox1);

        jLabel6.setText("Stav");
        jPanel1.add(jLabel6);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);

        jButton1.setText("Vytvořit úkol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Nevytvářet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nazev = jTextField1.getText();
        String popis = jTextArea1.getText();
        int id_priorita = jComboBox1.getSelectedIndex() + 1;
        int id_stav = jComboBox2.getSelectedIndex() + 1;
        if (id_priorita == 0) {
            id_priorita = 1;
        }
        try {
            String deadlineParse = jSpinner2.getValue() + "." + jSpinner3.getValue() + "." + jSpinner4.getValue() + "." + jSpinner1.getValue() + ":" + jSpinner5.getValue(); 
            SimpleDateFormat format1 = new SimpleDateFormat("dd.MM.yyyy.hh:mm");
            java.util.Date deadline = format1.parse(deadlineParse);
            PreparedStatement pstmt = OracleConnector.getConnection().prepareStatement("INSERT INTO"
                    + " SP_UKOLY(ID_UKOLU,NAZEV,POPIS,DATUM_VYTVORENI,DEADLINE,ID_PRIORITY,ID_STAV) "
                    + " VALUES(SP_SEQ_UKOLY.nextval, ?, ?, SYSDATE, ?, ?, ?)");
            pstmt.setString(1, nazev);
            pstmt.setString(2, popis);
            if(jCheckBox1.isSelected()){
                pstmt.setDate(3, new java.sql.Date(deadline.getTime()));
            } else {
                pstmt.setNull(3, java.sql.Types.DATE);
            }            
            pstmt.setInt(4, id_priorita);
            pstmt.setInt(5, id_stav);
            pstmt.executeUpdate();
            OracleConnector.getConnection().commit();
            //jLabel8.setText("Uživatel úspěšně vytvořen!");
            dispose();
        } catch (SQLException ex) {
            //  jLabel8.setText(ex.getClass().toString());
            ex.printStackTrace();
        } catch (ParseException ex) {
            Logger.getLogger(AddTaskDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
